# Generated by Django 5.2.8 on 2025-11-14 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_type', models.CharField(choices=[('trigonometry', 'Trigonometry'), ('custom_function', 'Custom Function'), ('ode', 'ODE Solver'), ('pde', 'PDE Solver'), ('calculus', 'Calculus'), ('statistics', 'Statistics')], max_length=20)),
                ('name', models.CharField(default='My Configuration', max_length=100)),
                ('config_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'simulation_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SimulationFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_type', models.CharField(choices=[('sin', 'Sine'), ('cos', 'Cosine'), ('tan', 'Tangent'), ('custom', 'Custom')], default='sin', max_length=10)),
                ('expression', models.TextField(blank=True, null=True)),
                ('amplitude', models.FloatField(default=1.0)),
                ('frequency', models.FloatField(default=1.0)),
                ('phase', models.FloatField(default=0.0)),
                ('color', models.CharField(default='#4f46e5', max_length=7)),
                ('visible', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('parameters', models.JSONField(default=dict)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='simulations.simulationconfiguration')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
