# Generated by Django 5.2.8 on 2025-11-20 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationconfiguration",
            name="ode_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rk4", "Runge-Kutta 4th Order"),
                    ("rk45", "Runge-Kutta-Fehlberg (RK45)"),
                    ("dopri5", "Dormand-Prince (DOPRI5)"),
                    ("bdf", "Backward Differentiation Formula (BDF)"),
                    ("radau", "Radau IIA (Implicit)"),
                    ("euler", "Euler Method"),
                    ("midpoint", "Midpoint Method"),
                    ("heun", "Heun Method"),
                    ("rk23", "Runge-Kutta 2nd/3rd Order"),
                    ("lsoda", "LSODA (Adaptive)"),
                ],
                default="rk4",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="simulationconfiguration",
            name="ode_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first_order", "First Order ODE"),
                    ("second_order", "Second Order ODE"),
                    ("system", "System of ODEs"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="simulationfunction",
            name="initial_conditions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="simulationfunction",
            name="variable_name",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="simulationfunction",
            name="function_type",
            field=models.CharField(
                choices=[
                    ("sin", "Sine"),
                    ("cos", "Cosine"),
                    ("tan", "Tangent"),
                    ("custom", "Custom"),
                    ("first_order_ode", "First Order ODE"),
                    ("second_order_ode", "Second Order ODE"),
                    ("system_ode", "System ODE"),
                ],
                default="sin",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ODESolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solution_data", models.JSONField(default=dict)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                ("computation_time", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("error", "Error"),
                            ("timeout", "Timeout"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "method_used",
                    models.CharField(
                        choices=[
                            ("rk4", "Runge-Kutta 4th Order"),
                            ("rk45", "Runge-Kutta-Fehlberg (RK45)"),
                            ("dopri5", "Dormand-Prince (DOPRI5)"),
                            ("bdf", "Backward Differentiation Formula (BDF)"),
                            ("radau", "Radau IIA (Implicit)"),
                            ("euler", "Euler Method"),
                            ("midpoint", "Midpoint Method"),
                            ("heun", "Heun Method"),
                            ("rk23", "Runge-Kutta 2nd/3rd Order"),
                            ("lsoda", "LSODA (Adaptive)"),
                        ],
                        default="rk4",
                        max_length=20,
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ode_solutions",
                        to="simulations.simulationconfiguration",
                    ),
                ),
            ],
            options={
                "ordering": ["-computed_at"],
            },
        ),
    ]
